[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x281d0491b2d7cd34bf9377212866a35afb2081322ff5b549d6e8ae142bec46cc'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]